"""add_defect_taxonomy

Revision ID: 29df8d29bcec
Revises: 006
Create Date: 2026-05-25 14:21:11.377628
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29df8d29bcec'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_tree_nodes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False, comment='0=root, 1=category, 2=subcategory, 3=leaf'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('defect_type', sa.String(length=64), nullable=True, comment='映射到 knowledge_entries.defect_type 的值'),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['defect_tree_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_tree_nodes_defect_type'), 'defect_tree_nodes', ['defect_type'], unique=False)
    op.create_index(op.f('ix_defect_tree_nodes_name'), 'defect_tree_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_defect_tree_nodes_parent_id'), 'defect_tree_nodes', ['parent_id'], unique=False)
    op.alter_column('anomaly_records', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment='patchcore / filter_classifier / rule_engine',
               existing_nullable=False)
    op.alter_column('anomaly_records', 'date_folder',
               existing_type=sa.VARCHAR(length=16),
               comment='YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('anomaly_records', 'crop_paths',
               existing_type=sa.TEXT(),
               comment='JSON 数组，存储所有异常裁剪图的 MinIO 路径',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='pending / embedded / noise / clustered / reviewed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('anomaly_records', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='单个异常被审核的时间（非 cluster 审核场景）',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'anomaly_review_status',
               existing_type=sa.VARCHAR(length=32),
               comment='real_defect / false_alarm — 噪声异常审核结果',
               existing_comment='real_defect / false_alarm',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'decision_reason',
               existing_type=sa.VARCHAR(length=64),
               comment='在线检测的 decision_reason: texture_anomaly / filter_classifier_suppressed 等',
               existing_comment='在线检测决策原因',
               existing_nullable=True)
    op.alter_column('clusters', 'representative_ids',
               existing_type=sa.TEXT(),
               comment='JSON array of anomaly IDs',
               existing_nullable=True)
    op.alter_column('clusters', 'centroid',
               existing_type=sa.TEXT(),
               comment='JSON array of centroid embedding',
               existing_nullable=True)
    op.alter_column('clusters', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='pending_review / reviewed / confirmed / ignored',
               existing_nullable=False,
               existing_server_default=sa.text("'pending_review'::character varying"))
    op.alter_column('clusters', 'review_status',
               existing_type=sa.VARCHAR(length=32),
               comment='real_defect / false_alarm',
               existing_nullable=True)
    op.alter_column('clusters', 'defect_type',
               existing_type=sa.VARCHAR(length=64),
               comment='wrinkle / scratch / reflection / stain / seam_shift',
               existing_nullable=True)
    op.alter_column('deployment_records', 'target',
               existing_type=sa.VARCHAR(length=64),
               comment='production_line / camera_group',
               existing_nullable=False)
    op.alter_column('deployment_records', 'deployment_status',
               existing_type=sa.VARCHAR(length=32),
               comment='active / rolled_back / superseded',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_embedding_vectors_embedding'), table_name='embedding_vectors', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('knowledge_entries', sa.Column('taxonomy_node_id', sa.String(length=32), nullable=True, comment='关联缺陷分类树节点'))
    op.alter_column('knowledge_entries', 'category',
               existing_type=sa.VARCHAR(length=64),
               comment='defect / false_alarm / camera_issue / lighting / process',
               existing_nullable=False)
    op.alter_column('knowledge_entries', 'action',
               existing_type=sa.VARCHAR(length=32),
               comment='ignore / NG / review_required',
               existing_nullable=False,
               existing_server_default=sa.text("'ignore'::character varying"))
    op.alter_column('knowledge_entries', 'camera_ids',
               existing_type=sa.TEXT(),
               comment='JSON array of camera IDs',
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'example_image_paths',
               existing_type=sa.TEXT(),
               comment='JSON array of MinIO paths',
               existing_nullable=True)
    op.create_index(op.f('ix_knowledge_entries_taxonomy_node_id'), 'knowledge_entries', ['taxonomy_node_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_entries', 'defect_tree_nodes', ['taxonomy_node_id'], ['id'])
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=32),
               comment='filter_classifier / embedding / yolo / patchcore',
               existing_nullable=False)
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='registered / validated / deployed / retired',
               existing_nullable=False,
               existing_server_default=sa.text("'registered'::character varying"))
    op.alter_column('review_records', 'action',
               existing_type=sa.VARCHAR(length=32),
               comment='confirm_defect / mark_false_alarm / rename / split / merge / ignore',
               existing_nullable=False)
    op.alter_column('rule_entries', 'rule_type',
               existing_type=sa.VARCHAR(length=32),
               comment='ignore / flag / escalate',
               existing_nullable=False)
    op.alter_column('rule_entries', 'condition_json',
               existing_type=sa.TEXT(),
               comment='JSON rule condition',
               existing_nullable=False)
    op.alter_column('rule_entries', 'camera_ids',
               existing_type=sa.TEXT(),
               comment='JSON array, null means all cameras',
               existing_nullable=True)
    op.alter_column('training_runs', 'new_anomaly_count',
               existing_type=sa.INTEGER(),
               comment='本次训练相比上次新增的 anomaly 数量',
               existing_comment='本次训练相比上次新增的 anomaly 数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_runs', 'new_anomaly_count',
               existing_type=sa.INTEGER(),
               comment='本次训练相比上次新增的 anomaly 数',
               existing_comment='本次训练相比上次新增的 anomaly 数量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_entries', 'camera_ids',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array, null means all cameras',
               existing_nullable=True)
    op.alter_column('rule_entries', 'condition_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON rule condition',
               existing_nullable=False)
    op.alter_column('rule_entries', 'rule_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='ignore / flag / escalate',
               existing_nullable=False)
    op.alter_column('review_records', 'action',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='confirm_defect / mark_false_alarm / rename / split / merge / ignore',
               existing_nullable=False)
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='registered / validated / deployed / retired',
               existing_nullable=False,
               existing_server_default=sa.text("'registered'::character varying"))
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='filter_classifier / embedding / yolo / patchcore',
               existing_nullable=False)
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_entries_taxonomy_node_id'), table_name='knowledge_entries')
    op.alter_column('knowledge_entries', 'example_image_paths',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of MinIO paths',
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'camera_ids',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of camera IDs',
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'action',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='ignore / NG / review_required',
               existing_nullable=False,
               existing_server_default=sa.text("'ignore'::character varying"))
    op.alter_column('knowledge_entries', 'category',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='defect / false_alarm / camera_issue / lighting / process',
               existing_nullable=False)
    op.drop_column('knowledge_entries', 'taxonomy_node_id')
    op.create_index(op.f('ix_embedding_vectors_embedding'), 'embedding_vectors', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('deployment_records', 'deployment_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='active / rolled_back / superseded',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('deployment_records', 'target',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='production_line / camera_group',
               existing_nullable=False)
    op.alter_column('clusters', 'defect_type',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='wrinkle / scratch / reflection / stain / seam_shift',
               existing_nullable=True)
    op.alter_column('clusters', 'review_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='real_defect / false_alarm',
               existing_nullable=True)
    op.alter_column('clusters', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='pending_review / reviewed / confirmed / ignored',
               existing_nullable=False,
               existing_server_default=sa.text("'pending_review'::character varying"))
    op.alter_column('clusters', 'centroid',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of centroid embedding',
               existing_nullable=True)
    op.alter_column('clusters', 'representative_ids',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of anomaly IDs',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'decision_reason',
               existing_type=sa.VARCHAR(length=64),
               comment='在线检测决策原因',
               existing_comment='在线检测的 decision_reason: texture_anomaly / filter_classifier_suppressed 等',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'anomaly_review_status',
               existing_type=sa.VARCHAR(length=32),
               comment='real_defect / false_alarm',
               existing_comment='real_defect / false_alarm — 噪声异常审核结果',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='单个异常被审核的时间（非 cluster 审核场景）',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='pending / embedded / noise / clustered / reviewed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('anomaly_records', 'crop_paths',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON 数组，存储所有异常裁剪图的 MinIO 路径',
               existing_nullable=True)
    op.alter_column('anomaly_records', 'date_folder',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('anomaly_records', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='patchcore / filter_classifier / rule_engine',
               existing_nullable=False)
    op.drop_index(op.f('ix_defect_tree_nodes_parent_id'), table_name='defect_tree_nodes')
    op.drop_index(op.f('ix_defect_tree_nodes_name'), table_name='defect_tree_nodes')
    op.drop_index(op.f('ix_defect_tree_nodes_defect_type'), table_name='defect_tree_nodes')
    op.drop_table('defect_tree_nodes')
    # ### end Alembic commands ###
