"""add_mask_refinement

Revision ID: 510d1b30d73b
Revises: b665eb69c9e9
Create Date: 2026-05-25 14:34:09.824518
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510d1b30d73b'
down_revision: Union[str, None] = 'b665eb69c9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_records', sa.Column('refined_crop_path', sa.String(length=512), nullable=True, comment='经 mask refinement 处理后的裁剪图 MinIO 路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_records', 'refined_crop_path')
    # ### end Alembic commands ###
