"""add_similarity_graph

Revision ID: b665eb69c9e9
Revises: 29df8d29bcec
Create Date: 2026-05-25 14:29:06.199384
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b665eb69c9e9'
down_revision: Union[str, None] = '29df8d29bcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_build_records',
    sa.Column('status', sa.String(length=32), nullable=False, comment='running / completed / failed'),
    sa.Column('total_anomalies', sa.Integer(), nullable=False),
    sa.Column('total_edges', sa.Integer(), nullable=False),
    sa.Column('k_neighbors', sa.Integer(), nullable=False, comment='每个节点的 K 近邻数'),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similarity_edges',
    sa.Column('source_anomaly_id', sa.String(length=32), nullable=False, comment='源异常ID'),
    sa.Column('target_anomaly_id', sa.String(length=32), nullable=False, comment='目标异常ID'),
    sa.Column('embedding_id', sa.String(length=32), nullable=False, comment='源 embedding ID'),
    sa.Column('rank', sa.Integer(), nullable=False, comment='KNN 中的排名 (1 = 最近邻)'),
    sa.Column('similarity_score', sa.Float(), nullable=False, comment='余弦相似度 (0-1, 越高越相似)'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarity_edges_source_anomaly_id'), 'similarity_edges', ['source_anomaly_id'], unique=False)
    op.create_index(op.f('ix_similarity_edges_target_anomaly_id'), 'similarity_edges', ['target_anomaly_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similarity_edges_target_anomaly_id'), table_name='similarity_edges')
    op.drop_index(op.f('ix_similarity_edges_source_anomaly_id'), table_name='similarity_edges')
    op.drop_table('similarity_edges')
    op.drop_table('graph_build_records')
    # ### end Alembic commands ###
